---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sequenceur/public_html
    - /bin/rsync -a --exclude='api/config.php' --exclude='.git' --exclude='.cpanel.yml' --exclude='scorm-packages' ./ $DEPLOYPATH/
